django:
  build: ../..
  dockerfile: Dockerfile.dev
  env_file: .env
  volumes:
    - "../../apps:/var/app/apps"
    - "../../dist:/var/app/dist"
    - "../../environments:/var/app/environments"
    - "../../project:/var/app/project"
  ports:
    - "80:8080"
    - "8010:8010"
